branch-defaults:
  master:
    environment: TelegramBTCRateBot-dev
    group_suffix: null
global:
  application_name: TelegramBTCRateBot
  branch: null
  default_ec2_keyname: TelegramBotBeanStalkKeyPair
  default_platform: PHP 7.1
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dev
  repository: null
  sc: git
  workspace_type: Application
