AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentConfigurationMetadata:
  DateCreated: '1506856743000'
  DateModified: '1506856837854'
  Description: Configuration created from the EB CLI using "eb config save".
EnvironmentTier:
  Name: WebServer
  Type: Standard
OptionSettings:
  aws:autoscaling:launchconfiguration:
    EC2KeyName: TelegramBotBeanStalkKeyPair
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.micro
    SecurityGroups:
    - rds-launch-wizard
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateEnabled: true
    RollingUpdateType: Health
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:container:php:phpini:
    composer_options: --no-dev
    document_root: /public
  aws:elasticbeanstalk:environment:
    LoadBalancerType: classic
  aws:elb:loadbalancer:
    CrossZone: true
  aws:elb:policies:
    ConnectionDrainingEnabled: true
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:eu-west-1::platform/PHP 7.1 running on 64bit
    Amazon Linux/2.5.0
